#######################################
# Main php container
#######################################
main:
  build: docker/main
  #dockerfile: Ubuntu-12.04 # Ubuntu 12.04 - PHP 5.3, LTS (precise)
  #dockerfile: Ubuntu-14.04  # Ubuntu 14.04 - PHP 5.5, LTS (trusty)
  #dockerfile: Ubuntu-15.04 # Ubuntu 15.04 - PHP 5.6 (vivid)
  dockerfile: Ubuntu-15.10 # Ubuntu 15.10 - PHP 5.6 (wily)
  #dockerfile: Ubuntu-HHVM  # Ubuntu 14.04 - HHVM (trusty)
  #dockerfile: Centos-7     # CentOS 7     - PHP 5.4
  links:
    - mysql
    #- postgres
    #mail-disabled - mail
    #- solr
    #- elasticsearch
    #- redis
    #- memcached
    #- ftp
    #satis-disabled - satis
  volumes:
    - ./docker/backup:/docker/backup
    - ./docker/bin:/docker/bin
    - ./docker/etc:/docker/etc
    - ./www:/docker/host-www
    - /tmp/debug/:/tmp/debug/
  volumes_from:
    - storage
    #satis-disabled - satis
  # cap and privileged needed for slowlog
  cap_add:
    - SYS_PTRACE
  privileged: true
  env_file:
    - docker/env.yml

#######################################
# Satis
#######################################
#satis-disabled satis:
#satis-disabled   build: docker/satis
#satis-disabled   hostname: satis
#satis-disabled   environment:
#satis-disabled     CRONTAB_FREQUENCY: "*/30 * * * *"
#satis-disabled     PRIVATE_REPO_DOMAIN_LIST: bitbucket.org gitlab.com github.com
#satis-disabled     VIRTUAL_HOST: satis.localhost
#satis-disabled   volumes:
#satis-disabled     - "~/.ssh/id_rsa:/var/tmp/id"
#satis-disabled     - "~/.dino-composer-satis/config/:/app/config/"
#satis-disabled     - "~/.dino-composer-satis/cache/:/root/.composer/"
#satis-disabled     - "~/.dino-composer-satis/web/:/satisfy/web/"
#satis-disabled   ports:
#satis-disabled     - 3000:3000
#satis-disabled     - 3080:80

#######################################
# Webserver
#######################################
web:
  build: docker/web
  dockerfile: Apache-Httpd # Apache HTTPd
  #dockerfile: Nginx       # Nginx
  ports:
    - 80:80
    - 8443:443
  links:
    - main
  volumes_from:
    - main
    - storage
  env_file:
    - docker/env.yml

#######################################
# MySQL server
#######################################
mysql:
  build: docker/mysql/  # MySQL, MariaDB or PerconaDB
  ports:
    - 13306:3306
  volumes_from:
    - storage
  volumes:
    - /tmp/debug/:/tmp/debug/
  env_file:
    - docker/env.yml

#######################################
# PostgreSQL server
#######################################
#postgres:
#  build: docker/postgres/
#  ports:
#    - 15432:5432
#  volumes_from:
#    - storage
#  env_file:
#    - docker/env.yml

#######################################
# Solr server
#######################################
#solr:
#  build: docker/solr/
#  ports:
#    - 18983:8983
#  volumes_from:
#    - storage
#  environment:
#    - SOLR_STORAGE=/data/solr/server-master/
#  env_file:
#    - docker/env.yml

#######################################
# Elasticsearch
#######################################
#elasticsearch:
#  build: docker/elasticsearch/
#  ports:
#    - 19200:9200
#    - 19300:9300
#  volumes_from:
#    - storage
#  env_file:
#    - docker/env.yml

#######################################
# Redis
#######################################
#redis:
#  build: docker/redis/
#  volumes_from:
#    - storage
#  env_file:
#    - docker/env.yml

#######################################
# Memcached
#######################################
#memcached:
#  build: docker/memcached/
#  volumes_from:
#    - storage
#  env_file:
#    - docker/env.yml

#######################################
# Mailcatcher
#######################################
#mail-disabled mail:
#mail-disabled   build: docker/mail/
#mail-disabled   ports:
#mail-disabled     - 1080:1080
#mail-disabled   env_file:
#mail-disabled     - docker/env.yml

#######################################
# FTP (vsftpd)
#######################################
#ftp:
#  build: docker/vsftpd/
#  volumes_from:
#    - storage
#  volumes:
#    - ./:/docker/
#    - /tmp/debug/:/tmp/debug/
#  env_file:
#    - docker/env.yml

#######################################
# Storage
#######################################
storage:
  build: docker/storage/
  volumes:
    - /data
